database: 
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"

email:
  address: "http://localhost:8081/send_email"
  sender: "josip.prgic@gmail.com"
